#!/bin/bash

: << =cut

=head1 NAME

ip_rtt_ - Wildcard-plugin to monitor IP round trip time

=head1 CONFIGURATION

  [ip_*]
    user root

=head2 ENVIRONMENT VARIABLES

This plugin does not use environment variables.

=head2 WILDCARD PLUGIN

This is a wildcard plugin.  To monitor traffic to or from an IP
address, link ip_<ipaddress> to this file.

For example,

  ln -s /usr/share/munin/plugins/ip_rtt_ \
        /etc/munin/plugins/ip_rtt_192.0.2.1

will monitor the IP 192.0.2.1.


=head1 BUGS

None known.

=head1 NOTES

This plugin is based on the ip_ plugin.

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf suggest

=head1 AUTHOR

Michal Ajduk <majduk@gmail.com>

=head1 LICENSE

Unknown.

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh
IP=${0##*/ip_rtt_}
ip_cmd=$(which ip)

if [[ "$1" == "autoconf" ]]; then
    if [[ -x "$ip_cmd" ]]; then
        rtt=$( $ip_cmd tcp_metrics show | head -n1 | awk '{ print $4 }' )
        if [ "$rtt" != "rtt" ]; then
            echo "$ip_cmd tcp_metrics show deas not work"
            exit 0
        else
            echo yes
            exit 0
        fi
    else
        echo "no ($ip_cmd not executable)"
        exit 0
    fi
fi

if [[ "$1" == "suggest" ]]; then
    exit 0
fi

if [[ "$1" == "config" ]]; then

    echo "graph_order rtt"
    title=$IP
    if [[ "$hostname" ]]; then
        title="$hostname"
    fi
    echo "graph_title $title RTT [us]"
    echo 'graph_args --base 1000'
    echo 'graph_vlabel RTT per ${graph_period}'
    echo 'graph_category network'
    echo 'rtt.label RTT'
    echo 'rtt.type DERIVE'
    echo 'rtt.min 0'
    echo 'rtt.cdef rtt,8,*'
    print_warning rtt
    print_critical rtt
    exit 0
fi;

$ip_cmd tcp_metrics show $IP | awk '{ print "rtt.value " strtonum($5) }' 

