#!/usr/bin/perl -w

=head1 NAME

md3200 - Munin plugin to monitor Dell MD3200 storage array.

=head1 DESCRIPTION
The MD3000i does not expose any performance data via SNMP. You can use SMCli which comes on the resource CD to get some basic stats from the MD3000i. 

/opt/dell/mdstoragemanager/client/SMcli <IP> -S -quick -c show virtualDisk [diskname] performanceStats; 

The output looks like this: 

=head1 CONFIGURATION

[md3200]
  env.controller 192.168.0.1
  env.smlcli /opt/dell/mdstoragemanager/client/SMcli
  env.disk disk1

=head1 MAGIC MARKERS

  #%# family=manual
  #%# capabilities=autoconf suggest

=head1 AUTHOR

Michal Ajduk

=head1 LICENSE

GPLv2

=cut

use Munin::Plugin;
use strict;

my $SMcli = $ENV{'smcli'} ? $ENV{'smcli'} : "/opt/dell/mdstoragesoftware/mdstoragemanager/client/SMcli";
my $host = $ENV{'controller'} ? $ENV{'controller'} : "md3200";
my $vdisk = $ENV{'disk'} ? $ENV{'disk'} : "disk1";
my $type = $ENV{'type'} ? $ENV{'type'} : "iops";
my $debug = $ENV{'debug'} ? $ENV{'debug'} : 0;

if ($ARGV[0] and $ARGV[0] =~ /^\s*config\s*$/i)
{
	  print "graph_title Storage $vdisk\n";
    print "graph_args --base 1000 -l 0\n";
    print "graph_vlabel $type\n";
    print "graph_category disk\n";
    if($type eq "percentage"){      
      print "readpercentage.label Read Percentage\n"; 
      print "cachehitpercentage.label Cache Hit Percentage\n";     
    }
    if($type eq "throughput"){
      print "currentkbpersecond.label Current KB/second\n"; 
      print "maximumkbpersecond.label Maximum KB/second\n";   
    }
    if($type eq "iops"){
      print "totalio.label Total IO\n";
      print "currentiopersecond.label Current IO/second\n"; 
      print "maximumiopersecond.label Maximum IO/second\n";  
    }         
    exit 0;
}



#Execute SMcli command
my $cmd = "$SMcli $host -S -quick -c \"show virtualDisk [\\\"$vdisk\\\"] performanceStats;\"";
if ($debug){
  print STDERR "$cmd \n";
}

if(!open(PIPE, "$cmd|"))
{
	die("Could not execute $cmd");
}

my $globalstatus = "";
my $extendedstatus = "";
my $vmdisk = "";
my $totalio = "";
my $readpercentage = "";
my $cachehitpercentage = "";
my $currentkbpersecond = "";
my $maximumkbpersecond = "";
my $currentiopersecond = "";
my $maximumiopersecond = "";
while(my $line = <PIPE>)
{
      if ($debug){
        print STDERR "$line\n";
      }
        chomp($line);
        if($line =~ /Virtual Disk/)
        {
                $globalstatus = $line;
	($vmdisk, $totalio, $readpercentage, $cachehitpercentage, $currentkbpersecond, $maximumkbpersecond, $currentiopersecond, $maximumiopersecond) = split (",", $line);
	$totalio =~ s/\"//g;
	$readpercentage =~ s/\"//g;
	$cachehitpercentage =~ s/\"//g;
	$currentkbpersecond =~ s/\"//g;
	$maximumkbpersecond =~ s/\"//g;
	$currentiopersecond =~ s/\"//g;
	$maximumiopersecond =~ s/\"//g;

    if($type eq "percentage"){
      print "readpercentage.value $readpercentage\n"; 
      print "cachehitpercentage.value $cachehitpercentage\n";     
    }
    if($type eq "throughput"){
      print "currentkbpersecond.value $currentkbpersecond\n"; 
      print "maximumkbpersecond.value $maximumkbpersecond\n";   
    }
    if($type eq "iops"){
      print "totalio.value $totalio\n";    
      print "currentiopersecond.value $currentiopersecond\n"; 
      print "maximumiopersecond.value $maximumiopersecond\n";  
    }   
        }
}


close(PIPE);
exit 0;
